AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Style/SpaceInsideBlockBraces: Space between { and | missing.
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

# Use the lambda method for multi-line lambdas.
Style/Lambda:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  EnforcedStyle: semantic

  FunctionalMethods:
    - map

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

# Unnecessary spacing detected
Style/ExtraSpacing:
  Enabled: false
