AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

  FunctionalMethods:
    - let
    - let!
    - map
    - subject

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*' # `class Api::V1::UsersController...` のように書きたいことがあるし、他の理由でネストすることはあまりないのではないか。

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
