AllCops:
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

  FunctionalMethods:
    - let
    - let!
    - given
    - given!
    - map
    - subject

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*' # `class Api::V1::UsersController...` のように書きたいことがあるし、他の理由でネストすることはあまりないのではないか。

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%w': '()'
    '%W': '()'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
