AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/Lambda:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  EnforcedStyle: semantic

  FunctionalMethods:
    - map

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Style/ExtraSpacing:
  Enabled: false
